# Generated by Django 5.1.6 on 2025-03-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finanzas", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingresoegreso",
            name="movimiento_inventario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.movimientoinventario",
            ),
        ),
        migrations.AddField(
            model_name="ingresoegreso",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.negocio"
            ),
        ),
    ]
