# Generated by Django 5.1.5 on 2025-03-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngresoEgreso',
        ),
    ]
