# Generated by Django 5.1.6 on 2025-03-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.negocio"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.negocio"
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.negocio"
            ),
        ),
    ]
