# Generated by Django 5.1.6 on 2025-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="negocio",
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
