# Generated by Django 5.1.5 on 2025-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='negocio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
